seed: 1
deterministic: true
num_workers: 8

train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /root/userfolder_new/20260527GaussiSR/GaussianSR-main/Dataset/FACE/CelebA/train/HR
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 16
      scale_min: 1.5
      scale_max: 8
      augment: true
      sample_q: 512
      batch_per_gpu: 4
  batch_size: 12
  scale_grouped_batching: true

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /root/userfolder_new/20260527GaussiSR/GaussianSR-main/Dataset/FACE/CelebA/val/HR
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: null
      scale_min: 4
      scale_max: 4
      augment: false
      sample_q: null
  batch_size: 1

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: gaussian-splatter-face-geometry-guided-appearance
  args:
    encoder_spec:
      name: edsr-face-geometry-guided-appearance
      args:
        no_upsampling: true
        use_pretrained: false
        n_resblocks: 16
        n_feats: 64
        shallow_depth: 4
        middle_depth: 10
        geometry_dim: 32
        fusion_dim: 64
        appearance_gate_init: 0.25
        guidance_dim: 32
        guidance_gate_init: 0.25
    dec_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]
    kernel_size: 5
    residual_feature_dim: 48
    residual_hidden_dim: 64
    scale_min: 1.5
    scale_max: 8
    max_rgb_residual: 0.20
    residual_gate_init: 0.50

optimizer:
  name: adam
  args:
    lr: 1.e-4

epoch_max: 5
multi_step_lr:
  milestones: [135, 270, 405, 540, 675, 810, 945, 1080, 1215]
  gamma: 0.5

epoch_val: 1
epoch_save: 5
eval_bsize: 10000
